[package]
name = "iced-chat"
version = "0.1.0"
edition = "2024"

[dependencies]

iced = "0.13"
#iced_native = "0.10"
#iced_wgpu = "0.13"
tokio = { version = "1.44.2", default-features = false, features = ["full"] }
